### PR TITLE
Queues: Add code for linear queues using Array

### PR DESCRIPTION
**Pull request by ShyrenMore**
Hey @chauhannaman98  I have added a menu-driven code for **linear queue using array**, 
The menu consists of functions like enqueue, dequeue and display.
I have also tried to explain each and every function using **comments**, at the end of program there is also a **sample output** .

### CODE REVIEW

**Comment by ShyrenMore** [comment]
Please add the hacktoberfest-accepted label for this PR, for some reason the hacktoberfest website is showing this repo as ineligible

**Review by chauhannaman98 — APPROVED** [review]
@ShyrenMore Thank you for contributing to the repository. It looks good.
I am looking forward to more PRs. :)

**Comment by chauhannaman98** [comment]
> Please add the hacktoberfest-accepted label for this PR, for some reason the hacktoberfest website is showing this repo as ineligible

okay!!

**Comment by ShyrenMore** [comment]
> @ShyrenMore Thank you for contributing to the repository. It looks good.
> I am looking forward to more PRs. :)

Yeah sure!

**Pull request merged**
